spring:
  profiles.active: dev

---
spring:
  profiles: dev
datasource:
  db-person:
      url: jdbc:h2:tcp://localhost/8082/dentist
      username: root
      password: root
      driver: org.h2.Driver
     ---

spring:
  profiles: prod
datasource:
  db-person:
      url: jdbc:mysql://localhost:3306/dentist
      username: username
      password: pwd
      driver: com.mysql.jdbc.Driver
